openapi: 3.0.3
info:
  title: Book Content Ingestion API
  description: API for ingesting book content and generating embeddings for RAG
  version: 0.1.0
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /api/ingestion/status:
    get:
      summary: Get ingestion pipeline status
      description: Returns the current status of the ingestion pipeline
      tags:
        - ingestion
      responses:
        '200':
          description: Ingestion pipeline status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionStatus'
  /api/ingestion/run:
    post:
      summary: Run the ingestion pipeline
      description: Triggers the full ingestion pipeline to process book content
      tags:
        - ingestion
      responses:
        '200':
          description: Ingestion started successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionResponse'
        '409':
          description: Ingestion already in progress
  /api/ingestion/verify:
    get:
      summary: Verify ingestion results
      description: Checks if embeddings and metadata were correctly stored
      tags:
        - ingestion
      responses:
        '200':
          description: Verification results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationResult'
components:
  schemas:
    IngestionStatus:
      type: object
      required:
        - status
        - progress
        - total_files
        - processed_files
      properties:
        status:
          type: string
          enum: [idle, processing, completed, failed]
          description: Current status of the ingestion pipeline
        progress:
          type: number
          minimum: 0
          maximum: 100
          description: Progress percentage
        total_files:
          type: integer
          description: Total number of files to process
        processed_files:
          type: integer
          description: Number of files processed so far
        error_message:
          type: string
          description: Error message if status is failed
    IngestionResponse:
      type: object
      required:
        - message
        - job_id
      properties:
        message:
          type: string
          description: Status message
        job_id:
          type: string
          description: Unique identifier for the ingestion job
    VerificationResult:
      type: object
      required:
        - vectors_stored
        - metadata_records
        - verification_passed
      properties:
        vectors_stored:
          type: integer
          description: Number of vectors stored in Qdrant
        metadata_records:
          type: integer
          description: Number of metadata records in Neon Postgres
        verification_passed:
          type: boolean
          description: Whether verification was successful
        details:
          type: object
          description: Additional verification details